### ISSUE TITLE
36以上版本，订阅GFWLIST之后，无法搜索单个规则。

### ISSUE THREAD

**Issue by jetyu** [agunchan/autoproxy#15]
换了以前的版本2013年的版本，就可以搜索GFWLIST里面单个规则（CTRL+F），然后添加例外。3月12号更新的不好使。

**Comment by liuruitv** [comment]
亲爱的朋友，感谢您对我们的支持！如果需要，我们的工作人员会在尽快联系您。

另外，我要告诉您的是，我决定免费与您分享一些我不为人知的营销与管理秘诀。这些秘诀帮助我的客户在市场取得了巨大的成功。我有一个单纯而美好的愿望，希望更多的人能了解和应用这些秘诀，创造更多的财富。

请点击下面的链接，进入下载页面，马上下载：http://liuruitv.com/
