### ISSUE TITLE
Firefox 36 中界面空白

### ISSUE THREAD

**Issue by yfdyh000** [agunchan/autoproxy#7]
TypeError: treeView.boxObject is null settings.js:668:2

黒仪大螃蟹的修改版 http://bbs.kafan.cn/thread-1783910-1-1.html 已经修复了这个问题。但他的版本好像因为做了功能增强，不能兼容继承已设置的代理规则。还有兴趣做一下修复吗。

**Comment by yfdyh000** [comment]
仅作备注：
大螃蟹版的规则兼容问题，手动替换配置的方法。
打开 about:config，选中  extensions.autoproxy.customProxy，复制值，粘贴到一个文本编辑器（如记事本）中。然后依次进行：
$ 替换为 ;0$  （增加新参数；HTTP代理为0）
socks;0$ 替换为 socks;1$  （SOCKS代理全部开启远程DNS）
结尾加一个 ;  （否则最后一个代理不能被识别；如果最后一个是SOCKS代理，加;1 ）
将结果复制粘贴回去。粘贴前可考虑备份。主要就是增加了一个;0/1参数标识“远程DNS”选项。

**Comment by yjxjn** [comment]
能不能修复一下tab utilities 啊 35不好使了哈。。。。跪求啊。

**Comment by yfdyh000** [comment]
@yjxjn 早就知道了，自己也在继续用并忍受。修复似乎挺麻烦的，没什么把握，所以一直没去尝试，在等其他人修复，但看上去也没人弄+_+。还没法承诺何时再去试试修。

**Comment by yjxjn** [comment]
@yfdyh000 自己也不会搞，我已经发信给Tab Utilities Lite CustomEdition的作者了。恳求加一个恢复标签页的功能。

**Comment by yfdyh000** [comment]
备注：私信作者后，1月18日的版本已经修复了规则兼容问题，不再有升级困难。

**Comment by yfdyh000** [comment]
@yjxjn 不清楚你指哪个功能。撤销到原位置我还没修好。撤销菜单刚修了一下，https://github.com/yfdyh000/tabutils/releases。撤销按钮我在35、36上没遇到问题。

**Comment by agunchan** [comment]
最近抽空看一下Fx36的问题，我自己已经很久不升级Fx了，所以也不知道这些问题。

**Comment by yfdyh000** [comment]
@agunchan 其实不修也没问题了，大螃蟹的版本目前还好，而且有些许增强。

**Comment by ihipop** [comment]
有空的时候还是看下firefox36的问题吧，为啥Chrome下这种软件一大堆 我可怜的FF基本就是没有了

**Comment by sunjw** [comment]
还是修一修吧，不要增强功能，就基本的就好了

**Comment by cssmagic** [comment]
@yfdyh000 
谢谢提供新的修复版。不知道这个黑蚁大螃蟹的版本有没有开源。

@agunchan 
谢谢你以前开发的修复版，很有帮助，辛苦了。如果有空，还请继续升级一下；如果没空，也没关系。

**Comment by yfdyh000** [comment]
@cssmagic 源码是开放的JavaScript，有疑虑可以自己对比一下差异。
螃蟹的确没有放在任何代码存储网站上，曾经私信沟通过，回复是：
> 至于源码放在github上的问题，
因为我这里访问github速度实在不怎么样，
而且也不能保证有能力、毅力、时间继续维护下去。
所以就只小打小闹地放到度盘上了。

**Comment by bigeagle** [comment]
@yfdyh000 给螃蟹推荐下gitcafe？对后来者也有帮助

**Comment by yfdyh000** [comment]
@bigeagle 我觉得主要问题是“不能保证维护”的心情吧。
国内的代码托管网站我不熟，你可以给贴吧的 [黒仪大螃蟹](http://www.baidu.com/p/黒仪大螃蟹) 私信建议一下。
不确定放在国内是否有法律和篡改风险，虽然几率很低。

**Comment by cssmagic** [comment]
@yfdyh000 
已联系到黒仪大螃蟹 (@Inaru)，并已开源： Inaru/autoproxy

感谢所有 AutoProxy 的开发者和维护者。

**Comment by bigeagle** [comment]
Thank you all !

**Comment by agunchan** [comment]
更新了新版本，只是修复了Fx36不能显示规则界面的问题。
http://fxthunder.com/files/autoproxy.xpi

**Comment by cssmagic** [comment]
@agunchan 谢谢，辛苦了！

**Comment by zjhxmjl** [comment]
@agunchan此版本不能支持ff 36.0.1

**Comment by digglife** [comment]
36.0.4 测试有效。多谢！
