### ISSUE TITLE
Settings disappeared after auto update to Firefox 36, again.

### ISSUE THREAD

**Issue by uspython** [agunchan/autoproxy#8]
Settings disappeared after auto update to Firefox 36,
又不能显示规则了，自动升级到FF36以后。

**Comment by Naco** [comment]
http://bbs.kafan.cn/thread-1783910-1-1.html

推荐黑蚁大螃蟹修改版。

**Comment by uspython** [comment]
多谢，已使用。一切恢复正常。

**Comment by agunchan** [comment]
更新了新版本，只是修复了Fx36不能显示规则界面的问题。
http://fxthunder.com/files/autoproxy.xpi

**Comment by linzhanyu** [comment]
Thank you!
